name: auto-publish

on:
  push:
    branches:
      - master

jobs:
  auto-update:  # job_id
    name: Markdown2HTML  # 作业显示在 GitHub 上的名称。
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # optional, default is 3.x
      - name: Convert markdown to html
        run: |
          pip install markdown2
          cd tools
          python markdown2html.py
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./results/htmls
